name: Update CPAN module manually

permissions: {}

on:
  workflow_dispatch:
    inputs:
      module:
        description: CPAN module
        required: true

jobs:
  bump-cpanfile:
    name: Bump cpanfile
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: ./update-cpan-module
        with:
          module: "${{ inputs.module }}"
