name: ChatOps for CPAN-related pull requests

env:
  commit-message-prefix: "chore(cpan): update"
  commit-message-regexp: "s/\\A[a-f0-9]+ chore\\(cpan\\): update ([a-zA-Z0-9_:']+) to .+\\z/$1/"

on:
  issue_comment:
    types:
      - created
  repository_dispatch:
    types:
      - recreated-command

jobs:
  dispatch:
    name: Dispatch events
    if: >-
      github.event_name == 'issue_comment'
      && github.actor == github.repository_owner
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: read
      issues: read
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - name: Get a module name from pull requests
        id: module
        env:
          GH_TOKEN: "${{ github.token }}"
          PR_ISSUE: "${{ github.event.issue.number }}"
          PR_PREFIX: "${{ env.commit-message-prefix }}"
          PR_REGEXP: "${{ env.commit-message-regexp }}"
        run: |
          set -xeuo pipefail

          gh pr checkout "${PR_ISSUE}"

          declare module
          module="$(git log --format=oneline --grep="${PR_PREFIX}" | head -n1 | perl -lpe "${PR_REGEXP}")"

          if [[ "${module:-}" =~ [^a-zA-Z0-9_\-:\'] ]]; then
            exit 1
          fi

          echo "module=${module}" >> "$GITHUB_OUTPUT"
        continue-on-error: true
      - name: Trigger recreate-command event
        if: steps.module.outcome == 'success'
        uses: peter-evans/slash-command-dispatch@9bdcd7914ec1b75590b790b844aa3b8eee7c683a # v5.0.2
        with:
          token: "${{ secrets.PAT }}"
          issue-type: pull-request
          commands: |
            recreate
          static-args: |
            module=${{ steps.module.outputs.module }}

  recreate-command:
    name: Recreate a pull request
    if: >-
      github.event_name == 'repository_dispatch'
      && github.event.client_payload.slash_command.command == 'recreate'
      && github.event.client_payload.slash_command.args.named.module != ''
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - uses: ./update-cpan-module
        with:
          module: "${{ github.event.client_payload.slash_command.args.named.module }}"
